# https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    helmVersion: v3
    repository: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: 9.4.0
  valuesFrom:
    - configMapKeyRef:
        name: prometheus-config
        namespace: monitoring
